version: '3.8'

services:
  # Service Express app
#  app:
#    image: node:18
#    container_name: express-app
#    working_dir: /usr/src/app
#    volumes:
#      - .:/usr/src/app
#      - /usr/src/app/node_modules
#    ports:
#      - '3000:3000'
#    command: npm run dev
#    depends_on:
#      - mongo
#    environment:
#      - MONGO_URL=mongodb://mongo:27017/bankdb
#    restart: unless-stopped

  # Service MongoDB
  mongo:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: bankdb
    restart: unless-stopped

volumes:
  mongo-data:
